### ISSUE TITLE
TickTick lists and Obsidian list name files two-way sync

### ISSUE THREAD

**Issue by gyuraam** [thesamim/TickTickSync#290]
ver. 1.1.12

In TickTick, tasks created in various lists are properly synced to the corresponding list name files in Obsidian.
However, tasks created in the list files within Obsidian are not recorded in the corresponding TickTick lists — they end up in the Inbox instead, requiring an extra step to manually assign them to the correct list.
Is there any way to restore the previous two-way sync between TickTick lists and Obsidian list name files?

**Comment by gyuraam** [comment]
It says "No default Project" in the bottom right corner.

Below is the content of my debug report.

```
{
  "general": {
    "enableFullVaultSync": false,
    "debugMode": true,
    "logLevel": "debug",
    "fileLinksInTickTick": "noLink",
    "taskLinksInObsidian": "noLink",
    "bkupFolder": "/",
    "skipBackup": true
  },
  "defaults": {
    "defaultProjectName": "Inbox",
    "defaultProjectId": "inbox124327982",
    "TickTickTasksFilePath": "Plan"
  },
  "syncControl": {
    "SyncProject": "",
    "tagAndOr": 1,
    "SyncTag": ""
  },
  "noteSetting": {
    "syncNotes": false,
    "noteDelimiter": "-------------------------------------------------------------"
  }
}
```

**Comment by thesamim** [comment]
Let's try this:

1. delete <your vault folder>\.obsidian\plugins\tickticksync\data.json
2. Log In
3. Got to settings -> Sync Control
4. check that default project is still "Inbox"
5. Set default folder location to "Plan".
6. set debug level to trace. 
7. Run First Sync
8. Navigate to one of your files and check if you see the list name as the project name
9. If yes: great, we fixed it.
10. If no: Send me your generated settings again, send me you console log.

**Comment by gyuraam** [comment]
I followed your instructions, but unfortunately, the bottom right corner of the file still shows "No default Project".


And below that is the settings information generated from the debug.

```
{
  "general": {
    "version": "1.1.12",
    "enableFullVaultSync": false,
    "debugMode": true,
    "logLevel": "trace",
    "fileLinksInTickTick": "noLink",
    "taskLinksInObsidian": "noLink",
    "bkupFolder": "/",
    "skipBackup": true
  },
  "defaults": {
    "defaultProjectName": "Inbox",
    "defaultProjectId": "inbox124327982",
    "TickTickTasksFilePath": "Plan"
  },
  "syncControl": {
    "SyncProject": "",
    "tagAndOr": 1,
    "SyncTag": ""
  },
  "noteSetting": {
    "syncNotes": false,
    "noteDelimiter": "-------------------------------------------------------------"
  }
}
```

Below is my console log — it might look a bit long since I included all entries related to TickTickSync.

`plugin:tickticksync:293 [TickTickSync][info][2025-08-03-08:51:30]: loading plugin "TickTickSync" v1.1.12
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:51:30]: {"baseUrl":"ticktick.com","token":"[154BB8FE91...] len: 336"}
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:51:30]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 8:51:30
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:51:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 8:51:31, took 462.50 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:56:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 8:56:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:56:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 8:56:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:56:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 8:56:31, took 516.10 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-08:56:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-08:56:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-08:56:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-08:56:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-08:56:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-08:56:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 8:56:32, took 811.60 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:01:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:01:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:01:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:01:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:01:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:01:31, took 508.30 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:01:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:01:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:01:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:01:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:01:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:01:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:01:32, took 764.20 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:06:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:06:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:06:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:06:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:06:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:06:31, took 508.00 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:06:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:06:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:06:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:06:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:06:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:06:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:06:32, took 875.00 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:11:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:11:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:11:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:11:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:11:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:11:31, took 487.40 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:11:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:11:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:11:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:11:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:11:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:11:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:11:32, took 768.60 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:16:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:16:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:16:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:16:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:16:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:16:31, took 477.90 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:16:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:16:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:16:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:16:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:16:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:16:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:16:32, took 748.60 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:21:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:21:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:21:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:21:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:21:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:21:31, took 473.20 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:21:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:21:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:21:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:21:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:21:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:21:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:21:32, took 741.10 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:26:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:26:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:26:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:26:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:26:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:26:31, took 484.10 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:26:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:26:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:26:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:26:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:26:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:26:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:26:32, took 768.30 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:31:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:31:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:31:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:31:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:31:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:31:31, took 481.90 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:31:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:31:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:31:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:31:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:31:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:31:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:31:32, took 754.70 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:36:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:36:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:36:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:36:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:36:32]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:36:32, took 782.70 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:36:32]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:36:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:36:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:36:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:36:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:36:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:36:32, took 1087.70 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:41:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:41:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:41:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:41:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:41:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:41:31, took 471.60 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:41:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:41:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:41:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:41:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:41:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:41:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:41:32, took 743.90 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:46:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:46:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:46:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:46:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:46:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:46:31, took 493.20 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:46:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:46:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:46:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:46:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:46:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:46:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:46:32, took 762.40 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:51:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:51:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:51:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:51:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:51:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:51:31, took 492.30 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:51:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:51:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:51:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:51:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:51:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:51:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:51:32, took 768.90 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:56:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 9:56:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:56:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 9:56:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:56:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 9:56:31, took 484.60 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-09:56:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:56:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:56:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-09:56:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-09:56:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-09:56:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 9:56:32, took 747.20 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:01:31]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 10:01:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:01:31]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 10:01:31
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:01:31]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 10:01:31, took 469.70 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-10:01:31]: Get All Resources as of: 2025-08-02T04:59:13.679Z
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:01:32]: We have:  0  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:01:32]: openTasks 0 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:01:32]: There are:  11  tasks in Cache.
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: New Files:  Object
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: 2. Study/집필 관련/키워드보다 중요한 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/Inbox.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/주요업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/단순업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/챙겨야 할 것.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/롱텀업무.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/버킷리스트.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/힐링.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/중요.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Plan/취미.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: 7. Daily_log/2025년/daily/25.08.02(토).md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: Clippings/대학원 오게 만드는 언어학 책들.md
plugin:tickticksync:74 [TickTickSync][debug][2025-08-03-10:01:32]: 7. Daily_log/2025년/daily/25.08.03(일).md
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:01:32]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 10:01:32, took 776.80 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-10:03:29]: Signed in Response:  Object
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:29]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 10:03:29
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:29]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 10:03:29, took 165.90 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-10:03:33]: Signed in Response:  Object
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:33]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 10:03:33
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:33]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 10:03:33, took 147.90 ms
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:56]: TickTick scheduled synchronization task started at 2025. 8. 3. 오전 10:03:56
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:56]: TickTick saveProjectsToCache started at 2025. 8. 3. 오전 10:03:56
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:03:56]: TickTick saveProjectsToCache completed at 2025. 8. 3. 오전 10:03:56, took 183.40 ms
plugin:tickticksync:1 [TickTickSync][debug][2025-08-03-10:03:56]: Get All Resources from the beginning of time. 
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:03:57]: We have:  13  recent tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:03:57]: openTasks 13 closedTasks 0
plugin:tickticksync:34 [TickTickSync][debug][2025-08-03-10:03:57]: There are:  11  tasks in Cache.
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:57]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:57]: adding to  Plan/단순업무.md
plugin:tickticksync:43 [TickTickSync][debug][2025-08-03-10:03:57]: Processing File:  Plan/단순업무.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:58]: === Plan/단순업무.md Array(1) Completed adding task(s).
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:58]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:58]: adding to  Plan/챙겨야 할 것.md
plugin:tickticksync:43 [TickTickSync][debug][2025-08-03-10:03:58]: Processing File:  Plan/챙겨야 할 것.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: === Plan/챙겨야 할 것.md Array(1) Completed adding task(s).
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: adding to  Plan/중요.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: adding to  Plan/중요.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: adding to  Plan/중요.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: adding to  Plan/중요.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:03:59]: adding to  Plan/중요.md
plugin:tickticksync:43 [TickTickSync][debug][2025-08-03-10:03:59]: Processing File:  Plan/중요.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: === Plan/중요.md Array(5) Completed adding task(s).
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: taskFile null
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:02]: adding to  Plan/취미.md
plugin:tickticksync:43 [TickTickSync][debug][2025-08-03-10:04:02]: Processing File:  Plan/취미.md
plugin:tickticksync:41 [TickTickSync][debug][2025-08-03-10:04:05]: === Plan/취미.md Array(6) Completed adding task(s).
plugin:tickticksync:293 [TickTickSync][debug][2025-08-03-10:04:06]: TickTick scheduled synchronization task completed at 2025. 8. 3. 오전 10:04:06, took 9451.00 ms`

**Comment by gyuraam** [comment]
No, I use TickTick. 
Since my language setting is set to Korean, "Inbox" is displayed as "기본함" on the TickTick website.
However, when imported into Obsidian, the file name appeared as "Inbox".

**Comment by thesamim** [comment]
Sorry, I'm not able to reproduce the issue. 

I did find another problem. I didn't think it was related, but it might be. Just in case, could you please test with this:

1. save your <your vault>\.obsidian\plugins\tickticksync contents somewhere
2. unzip the attached into that folder.

[TickTickSync-1.1.13-beta.zip](https://github.com/user-attachments/files/21581644/TickTickSync-1.1.13-beta.zip)

If you're still seeing the problem, please copy/paste settings again (I've added a couple more settings that might help me understand what's going on....)

**Comment by gyuraam** [comment]
I’ve resolved the issue! After setting the default project to "None" and creating a new task in each folder on TickTick, then syncing, each file in Obsidian correctly linked to its corresponding folder. Thank you!
